2020-09-29 17:26:02,287 INFO: request.url:http://mp.zjswdl.cn/wx/wxsvr [in C:\workspace\pythonWorkspace\workblog\app\wx\routes.py:135]
2020-09-29 17:26:02,330 ERROR: (sqlite3.OperationalError) table wechat_message has no column named from_user
[SQL: INSERT INTO wechat_message (id, from_user, message_type, message_body, created_date) VALUES (?, ?, ?, ?, ?)]
[parameters: (0, 'fromUser', 'voice', b'<xml>\r\n  <ToUserName><![CDATA[toUser]]></ToUserName>\r\n  <FromUserName><![CDATA[fromUser]]></FromUserName>\r\n  <CreateTime>1357290913</CreateTim ... (28 characters truncated) ... ice]]></MsgType>\r\n  <MediaId><![CDATA[media_id]]></MediaId>\r\n  <Format><![CDATA[Format]]></Format>\r\n  <MsgId>1234567890123456</MsgId>\r\n</xml>', '2020-09-29 17:26:02.329974')]
(Background on this error at: http://sqlalche.me/e/e3q8) [in C:\workspace\pythonWorkspace\workblog\app\wx\routes.py:216]
2020-09-29 17:26:20,180 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:84]
2020-09-29 17:26:21,206 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:84]
2020-09-29 17:26:25,538 INFO: request.method:POST [in C:\workspace\pythonWorkspace\workblog\app\wx\routes.py:134]
2020-09-29 17:26:25,539 INFO: request.url:http://mp.zjswdl.cn/wx/wxsvr [in C:\workspace\pythonWorkspace\workblog\app\wx\routes.py:135]
2020-09-29 17:26:25,567 ERROR: (sqlite3.OperationalError) table wechat_message has no column named from_user
[SQL: INSERT INTO wechat_message (id, from_user, message_type, message_body, created_date) VALUES (?, ?, ?, ?, ?)]
[parameters: (0, 'fromUser', 'voice', b'<xml>\r\n  <ToUserName><![CDATA[toUser]]></ToUserName>\r\n  <FromUserName><![CDATA[fromUser]]></FromUserName>\r\n  <CreateTime>1357290913</CreateTim ... (28 characters truncated) ... ice]]></MsgType>\r\n  <MediaId><![CDATA[media_id]]></MediaId>\r\n  <Format><![CDATA[Format]]></Format>\r\n  <MsgId>1234567890123456</MsgId>\r\n</xml>', '2020-09-29 17:26:25.566401')]
(Background on this error at: http://sqlalche.me/e/e3q8) [in C:\workspace\pythonWorkspace\workblog\app\wx\routes.py:216]
2020-09-29 17:27:54,781 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:84]
2020-09-29 17:27:56,454 INFO: request.method:POST [in C:\workspace\pythonWorkspace\workblog\app\wx\routes.py:134]
2020-09-29 17:27:56,455 INFO: request.url:http://mp.zjswdl.cn/wx/wxsvr [in C:\workspace\pythonWorkspace\workblog\app\wx\routes.py:135]
2020-09-29 17:27:56,488 ERROR: (sqlite3.OperationalError) table wechat_message has no column named from_user
[SQL: INSERT INTO wechat_message (id, from_user, message_type, message_body, created_date) VALUES (?, ?, ?, ?, ?)]
[parameters: (0, 'fromUser', 'voice', '<xml>\r\n  <ToUserName><![CDATA[toUser]]></ToUserName>\r\n  <FromUserName><![CDATA[fromUser]]></FromUserName>\r\n  <CreateTime>1357290913</CreateTime ... (27 characters truncated) ... ice]]></MsgType>\r\n  <MediaId><![CDATA[media_id]]></MediaId>\r\n  <Format><![CDATA[Format]]></Format>\r\n  <MsgId>1234567890123456</MsgId>\r\n</xml>', '2020-09-29 17:27:56.487809')]
(Background on this error at: http://sqlalche.me/e/e3q8) [in C:\workspace\pythonWorkspace\workblog\app\wx\routes.py:216]
2020-10-05 19:43:41,502 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 19:43:42,642 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 19:46:03,974 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 19:46:29,083 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 19:47:29,490 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 19:58:32,868 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:00:13,762 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:01:46,751 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:13:14,681 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:14:57,831 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:15:47,187 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:18:18,694 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:21:35,463 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:33:34,131 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:33:54,000 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:34:00,590 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:35:10,790 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-05 20:38:16,565 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
2020-10-18 15:27:25,646 INFO: Workblog startup... [in C:\workspace\pythonWorkspace\workblog\app\__init__.py:89]
